notifications:
    email: false
language: node_js
node_js:
    - "lts/*"
cache:
    yarn: true
    directories:
        - "node_modules"
after_script: "yarn add -D coveralls && cat ./coverage/lcov.info | coveralls"
